// <auto-generated />
using System;
using MailMan.Dal.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MailMan.Dal.Migrations
{
    [DbContext(typeof(MailManContext))]
    partial class MailManContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MailMan.Dal.Entities.MailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailedMessage")
                        .HasColumnType("text");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MailMessages");
                });

            modelBuilder.Entity("MailMan.Dal.Entities.Recipient", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("Recipients");
                });

            modelBuilder.Entity("MailMessageRecipient", b =>
                {
                    b.Property<Guid>("MailMessagesId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientsEmail")
                        .HasColumnType("text");

                    b.HasKey("MailMessagesId", "RecipientsEmail");

                    b.HasIndex("RecipientsEmail");

                    b.ToTable("MailMessageRecipient");
                });

            modelBuilder.Entity("MailMessageRecipient", b =>
                {
                    b.HasOne("MailMan.Dal.Entities.MailMessage", null)
                        .WithMany()
                        .HasForeignKey("MailMessagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MailMan.Dal.Entities.Recipient", null)
                        .WithMany()
                        .HasForeignKey("RecipientsEmail")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
